# SPDX-License-Identifier: GPL-3.0-only

org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true

mod_id=qizhang_player_leash
mod_name=Player's Tether_Easter Egg Version
mod_license=GPL-3.0-only AND MIT AND CC-BY-SA-4.0
mod_version=1.1.6
mod_group_id=qizhang.playerleash
mod_authors=QiZhang
mod_description=Leash other players with directional server rules and a six-layer taming easter egg.
archives_name=players-tether-easter-egg

fabric_loader_version=0.19.3
fabric_api_121_version=0.116.15+1.21.1
fabric_api_120_version=0.92.11+1.20.1
neoforge_121_version=21.1.244
neoforge_120_version=1.20.1-47.1.106
forge_121_version=52.1.0
forge_120_version=47.4.10
